#@ load("@ytt:data", "data")
#@ load("helpers.star", "get_image_name")

apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: #@ get_image_name()
  path: ./0
  kubectlBuildKit:
    build:
      file: #@ "../1/Dockerfile." + data.values.programming_language_runtime

#@ if/end data.values.push_images_repo:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
destinations:
- image: #@ get_image_name()
  newImage: #@ data.values.push_images_repo

